language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t mickiehsu2008/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mickiehsu2008/docker-react npm run test